spring:
  jpa:
#    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # create: 프로그램 실행 시마다 새로 생성하고 종료 시 드롭. Create 한 번 치고 중지한 다음 값을 none으로 바꾸면 생성한 테이블 그대로 유지 가능
      ddl-auto: update
        # 테이블에 매핑 시 camel case를 underscore로 변경하는 것이 디폴트인데
        # 변수 이름 그대로 사용 가능하도록 설정
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show-sql: true
#        dialect: org.hibernate.dialect.H2Dialect


  h2:
    console:
      enabled: true
      path: /testdb
  datasource:
    # jdbc:h2:file: 파일로 h2 db를 관리하겠다
    # ~/…/xxdb xxdb 파일이 저장된 위치
    url: jdbc:h2:~/h2db/testdb;MODE=MySQL
#    url: jdbc:h2:~/h2db/testdb?serverTimezone=Asia/Seoul;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE;FILE_LOCK=NO
    driver-class-name: org.h2.Driver
    username: test
    password:
