-- 카테고리 테이블
CREATE TABLE CATEGORY (
    ID BIGINT NOT NULL, -- 카테고리 아이디
    CATEGORY_NM VARCHAR(20) NULL, -- 카테고리명
    CATEGORY_CD VARCHAR(10) NULL -- 카테고리 코드
);

ALTER TABLE CATEGORY
    ADD CONSTRAINT PK_CATEGORY -- 카테고리 기본키
    PRIMARY KEY (
        ID -- 카테고리 아이디
    );

ALTER TABLE CATEGORY
    MODIFY COLUMN ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID';



-- 원본 데이터셋 테이블
CREATE TABLE ORIGIN_DATASET (
	ID BIGINT NOT NULL COMMENT '원본 데이터셋 아이디',
	OD_NM VARCHAR(100) NULL COMMENT '원본 데이터셋 폴더명',
	OD_DIR VARCHAR(400) NULL COMMENT '원본 데이터셋 폴더 경로',
	CATEGORY_CD VARCHAR(10) NULL COMMENT '카테고리 코드',
	CREATE_DATE TIMESTAMP NULL COMMENT '업로드날짜'
);

ALTER TABLE ORIGIN_DATASET
	ADD CONSTRAINT PK_ORIGIN_DATASET
	PRIMARY KEY (
		ID -- 원본 데이터셋 아이디
	);

ALTER TABLE ORIGIN_DATASET
	MODIFY COLUMN ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID';



-- 원본 데이터 파일 테이블
CREATE TABLE ORIGIN_FILE (
	ID BIGINT NOT NULL COMMENT '원본 파일 아이디',
	OF_DIR VARCHAR(400) NULL COMMENT '원본 파일 경로',
	OF_WAV_NM VARCHAR(100) NULL COMMENT '원본 wav 파일명',
	OF_WAV_SIZE BIGINT NULL COMMENT '원본 wav 파일크기',
	OF_TXT_NM VARCHAR(100) NULL COMMENT '원본 TXT파일명',
	OF_TXT_SIZE BIGINT NULL COMMENT '원본 TXT파일크기',
	OF_META_NM VARCHAR(100) NULL COMMENT '메타데이터파일명',
	CREATE_DATE TIMESTAMP NULL COMMENT '업로드날짜',
	OD_ID BIGINT NOT NULL COMMENT '원본 데이터셋 아이디'
);

ALTER TABLE ORIGIN_FILE
	ADD CONSTRAINT PK_ORIGIN_FILE
	PRIMARY KEY (
		ID
	);

ALTER TABLE ORIGIN_FILE
	MODIFY COLUMN ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID';

ALTER TABLE ORIGIN_FILE
	ADD CONSTRAINT FK_ORIGIN_DATASET_TO_ORIGIN_FILE
	FOREIGN KEY (
		OD_ID
	)
	REFERENCES ORIGIN_DATASET (
		ID
	);



-- 수정본 데이터셋 테이블
CREATE TABLE REVISION_DATASET (
	ID BIGINT NOT NULL COMMENT '수정본 데이터셋 아이디',
	RD_NM VARCHAR(100) NULL COMMENT '데이터셋 폴더명',
	RD_DIR VARCHAR(400) NULL COMMENT '데이터셋 폴더 경로',
	CATEGORY_CD VARCHAR(10) NULL COMMENT '카테고리 코드',
	CREATE_DATE TIMESTAMP NULL COMMENT '업로드날짜',
	OD_ID BIGINT NOT NULL COMMENT '원본 데이터셋 아이디'
);


ALTER TABLE REVISION_DATASET
	ADD CONSTRAINT PK_REVISION_DATASET
	PRIMARY KEY (
		ID -- 수정본 데이터셋 아이디
	);

ALTER TABLE REVISION_DATASET
	MODIFY COLUMN ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID';

ALTER TABLE REVISION_DATASET
	ADD CONSTRAINT FK_ORIGIN_DATASET_TO_REVISION_DATASET
	FOREIGN KEY (
		OD_ID
	)
	REFERENCES ORIGIN_DATASET ( -- 원본 데이터셋
		ID -- 원본 데이터셋 아이디
	);



-- 수정본 데이터 파일 테이블
CREATE TABLE REVISION_FILE (
	ID BIGINT NOT NULL COMMENT '수정본 파일 아이디',
	OF_ID BIGINT NOT NULL COMMENT '원본 파일 아이디',
	RF_DIR VARCHAR(400) NULL COMMENT '수정본 파일 경로',
	RF_WAV_NM VARCHAR(100) NULL COMMENT '수정본 wav파일명',
	RF_WAV_SIZE BIGINT NULL COMMENT '수정본 wav파일크기',
	RF_TXT_NM VARCHAR(100) NULL COMMENT '수정본 TXT파일명',
	RF_TXT_SIZE BIGINT NULL COMMENT '수정본 TXT파일크기',
	RF_META_NM VARCHAR(100) NULL COMMENT '메타데이터파일명',
	CREATE_DATE TIMESTAMP NULL COMMENT '업로드날짜',
	RD_ID BIGINT NOT NULL COMMENT '수정본 데이터셋 아이디'
);

ALTER TABLE REVISION_FILE
	ADD CONSTRAINT PK_REVISION_FILE
	PRIMARY KEY (
		ID
	);

ALTER TABLE REVISION_FILE
	MODIFY COLUMN ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID';

ALTER TABLE REVISION_FILE
	ADD CONSTRAINT FK_ORIGIN_FILE_TO_REVISION_FILE
	FOREIGN KEY (
		OD_ID
	)
	REFERENCES ORIGIN_FILE (
		ID
	);

ALTER TABLE REVISION_FILE
	ADD CONSTRAINT FK_REVISION_DATASET_TO_REVISION_FILE
	FOREIGN KEY (
		RD_ID
	)
	REFERENCES REVISION_DATASET (
		ID
	);
